version: '2'
services:
  docker-nginx:
    build: ./docker-nginx
    container_name: docker-nginx
    environment:
      DOCKER: 'true'
    ports:
      - "81:80"
    depends_on:
      - docker-storage
      - docker-php
    volumes_from:
      - docker-storage

  docker-php:
    build: ./docker-php
    container_name: docker-php
    depends_on:
      - docker-storage
    volumes_from:
      - docker-storage

  docker-storage:
    build: ./docker-storage
    container_name: docker-storage
    volumes:
    - ./docker-storage/container-files/var/log/nginx/:/var/log/nginx
    - ./docker-storage/container-files/var/log/php-fpm:/var/log/php-fpm
    - ./docker-storage/container-files/var/www/html:/var/www/html
    # - ./docker-storage/container-files/var/run:/var/run
